FROM python:3.11-slim-bullseye
RUN apt-get clean && apt-get -y update
RUN apt-get -y install build-essential
RUN apt-get -y install libpq-dev unixodbc-dev
WORKDIR /app

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

COPY src ./src
COPY ./main.py ./

ENTRYPOINT ["python", "main.py"]